### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [gaearon/ama#1]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by gaearon** [comment]
### Hardware

I used to have 17'' MBP, later switched to 15''' MBP retina. Now I use the New Macbook. It's kinda slower but I have mild back pains and the New Macbook is a bliss because it's just so light and yet has Retina screen. I can't work with non-Retina screens anymore.

### Editor

I use Sublime Text 3 with [Spacegray](https://github.com/kkga/spacegray) UI theme which my friend [Gadzhi](https://github.com/kkga) created. (Redux is finally catching up in popularity to it!)

Instead of the syntax themes that go with it, I use [Oceanic Next](https://github.com/voronianski/oceanic-next-color-scheme) which is perfect for [Babel JavaScript language definition](https://github.com/babel/babel-sublime).

<img width="1042" alt="screen shot 2015-09-14 at 18 25 30" src="https://cloud.githubusercontent.com/assets/810438/9853827/57a770b8-5b0e-11e5-8817-207827ec4bb3.png">

### Terminal

Nothing fancy. I'm bad at terminaling and I don't know how to write bash scripts or even use basic utils like `xargs`. Therefore I use Terminal that ships with OS X and [fish shell](http://fishshell.com/) because it autocompletes on tab and has a nice coloring. Of course for this reason copy-pasting bash commands doesn't work and I have to replace `&&` with `; and` all the time.

<img width="1022" alt="screen shot 2015-09-14 at 18 30 30" src="https://cloud.githubusercontent.com/assets/810438/9853885/b2267930-5b0e-11e5-97ce-6302abc218f7.png">

### Font

Microsoft [Consolas](http://www.fonts.com/font/microsoft-corporation/consolas) has always been my favorite. I come from .NET development background so there's that.

I prefer large font size everywhere even though I have perfect (?) vision. Small font just irritates me. I also like how large font forces me to only consider the closest context so I have to write smaller functions.

### Tools

Very boring and standard.

For webdev:
- Chrome
- React
- Babel
- `n` to switch Node versions
- ESLint (see [Lint Like It's 2015](https://medium.com/@dan_abramov/lint-like-it-s-2015-6987d44c5b48))
- Twitter (seriously, I spend 20% of dev time there)

For life:
- Slack, in particular [Reactiflux](http://reactiflux.com) to chat about my projects
- Gifgrabber, Recordit or Cloudapp for taking gifs (whatever works best for a particular gif)

**Comment by prakhar1989** [comment]
>  I also like how large font forces me to only consider the closest context so I have to write smaller functions.

Neat hack!

**Comment by bookercodes** [comment]
Awesome answer. I was using _Spacegrey_ already but now I'm using _Oceanic Next_ as well - it looks great:

![](https://i.imgur.com/EMgc40l.png)

**Comment by gaearon** [comment]
Oh, and I also have

```
    "line_padding_bottom": 1,
    "line_padding_top": 1,
```

in Sublime settings.

**Comment by vdemin** [comment]
Are you using a Git GUI, or doing everything in the command line?

**Comment by gaearon** [comment]
> Are you using a Git GUI, or doing everything in the command line?

Command line, as I screwed up a couple of times using different clients. I also often use commands like `reset --hard`, `--amend` etc, and it's usually easier to do via command line.

**Comment by djyde** [comment]
A few months passed, did you change your dev environment? It seem you had changed your editor from ST to Atom. What made you change?

**Comment by gaearon** [comment]
I use Atom at work to help dogfood Nuclide at Facebook. I still prefer Sublime because I’m more efficient in it but it’s a matter of habit and I hope to switch within a year.

I did, however, start using Operator Mono instead of Consolas:

![](https://pbs.twimg.com/media/Cbh2GT1WcAA4Wty.png:large)

Warning: it’s somewhat expensive. I got it as a generous gift.

**Comment by O4epegb** [comment]
> I have perfect (?) vision.

What is your secret? How is this possible to have good vision while programming so much and generally spend time beside computer?

**Comment by rafayepes** [comment]
Which syntax theme do you use with Atom? I like Oceanic Next but didn't find anything similar for Atom (there is actually an Oceanic theme for Atom, but to me doesn't look like Oceanic Next for Sublime).

**Comment by fa7ad** [comment]
Try **zsh** with _oh-my-zsh_ or _prezto_ for your terminal shell (and yes, it autocompletes :smile: ). I switched from bash a year ago, now can't live without it :D

![screenshot from 2016-08-31 15-22-37](https://cloud.githubusercontent.com/assets/7447677/18123256/ef4b6ede-6f8e-11e6-9855-8e8bf0334ad6.png)

**Comment by gaearon** [comment]
> What is your secret? How is this possible to have good vision while programming so much and generally spend time beside compu

Haha too late. My right eye is -0.5 now so things in distance get a little blurry.

**Comment by kasperpeulen** [comment]
> Try zsh with oh-my-zsh or prezto for your terminal shell (and yes, it autocompletes 😄 ). I switched from bash a year ago, now can't live without it :D

Not wanting to start a fanboy war here :P But fish autocomplets is a lot better than oh-my-zsh. It also autocompletes by using your command history.

**Comment by fa7ad** [comment]
@kasperpeulen maybe, but isn't fish incompatible with most other shells?

**Comment by kasperpeulen** [comment]
@fa7ad Yes, that is a pain. I actually don't use fish anymore, because of that. But I do think fish shines as it comes to autocompletion.

**Comment by Whoaa512** [comment]
@kasperpeulen, You can achieve something close to the autocomplete command history stuff with a few lines in your `~/.inputrc`.

https://coderwall.com/p/oqtj8w/the-single-most-useful-thing-in-bash

**Comment by CassianoSF** [comment]
How you change de params/args font? You have them italic like.
I got the spacegray + oceanic next + JavaScript(Babel) syntax
