### ISSUE TITLE
What do you do to stay informed on all the technologies and practices?

### ISSUE THREAD

**Issue by viczam** [gaearon/ama#11]

**Comment by gaearon** [comment]
I follow people on Twitter and keep an eye out for things that make a splash there.

**Comment by prakhar1989** [comment]
No HN? :open_mouth:

**Comment by gaearon** [comment]
No, I can't stand it. I used to visit it often in the past, but lately, every time I come there it's the same stuff being discussed with [the same patterns of comments](http://bradconte.com/files/misc/HackerNewsParodyThread/), and they're often toxic, subtly mean or privileged.

**Comment by prakhar1989** [comment]
Haha! I've seen various HN parodies before but this is by far the best. Thanks for the link!

**Comment by gaearon** [comment]
I found that anything good on HN will find its way on Twitter anyway.

**Comment by prakhar1989** [comment]
That's true - most of the stories do make their way to you some way or the other (newsletters, Twitter, Medium etc). However, I still frequent HN because of the comments (when they are not hostile / caustic). I've been a regular for quite a while so I've gotten a knack for filtering the signal from the noise ;)
