### ISSUE TITLE
What are your least favorite parts of Redux and React?

### ISSUE THREAD

**Issue by timuric** [gaearon/ama#29]
We all know that you are a React enthusiast, but are there things in React and Redux that you personally dislike or think could be done better? Those could be fundamental aspects or just small details.

**Comment by gaearon** [comment]
## React
- Context used to be very flaky (will mostly be solved in 0.14)
- Duplicate Reacts don't work together (should be much better in 0.15 where `react-dom` is truly separate thing, and many `react`s can coexist)
- Weird error messages when DOM is invalid, e.g. nested links (will be solved in 0.14)
- It's currently hard to write universal components against React and React Native (will be solved soon after 0.14)
- Focus management is imperative, so it forces us back into DOM land
- Higher-order components are sometimes a pain because people keep wanting to have `refs` or fire methods and you can't teach them to stop doing that because they have valid reasons (e.g. see focus management)

I can't think of anything else much. I'm pretty satisfied with React, and while there are frameworks like [Cycle](http://cycle.js.org) that [hate on `setState()`](http://staltz.com/dont-react/#/), you can [adapt Cycle's patterns to React just fine](https://github.com/pH200/cycle-react) if they indeed prove better.

## Redux
- It doesn't solve data fetching like Relay
- Functional API and extensive use of higher-order functions turns off beginners
- It's not "purely functional" like Cycle either—feels like I'm doing something dirty
- I'm not very satisfied with putting async API calls and the middleware system, but it's [still the best](https://github.com/rackt/redux/pull/569#issuecomment-133241762) we could come up with

These are conscious fundamental limitations by design and scope, of course. If I could fix them, I would have already.
