### ISSUE TITLE
If you could just continue doing open-source like you have been, would you?

### ISSUE THREAD

**Issue by ghost** [gaearon/ama#44]
i.e. if you were constantly funded via patreon or something similiar

**Comment by gaearon** [comment]
No, for two reasons:
- Maintaining open source projects is a constant toll on your psyche and sometimes you need to take a break.
- Being able to switch to work on a product is essential because it gives you the insights for creating libraries and tools. Otherwise you're just going to become a library astronaut.

**Comment by nickdima** [comment]
> Being able to switch to work on a product is essential because it gives you the insights for creating libraries and tools. Otherwise you're just going to become a library astronaut.

That's so true!
@gaearon come work with us at [Musixmatch](https://www.musixmatch.com/) :)
