### ISSUE TITLE
Did you go to college?

### ISSUE THREAD

**Issue by eush77** [gaearon/ama#47]
Do you regret it?

**Comment by gaearon** [comment]
I went to a uni right after school but I dropped out on the second year. I did it because I was a bad student and didn’t really care about my curriculum, teachers, or other students.

This was the right choice for me, but only considering my circumstances described below. I don’t think dropping out is _always_ a good idea—it’s only good if you see that you’re wasting yours and everyone’s time, and if the market proves you’re not being delusional.

What it was like for me:
- There wasn’t hardly any programming the first year, and some really ancient programming (vanilla C inside NetBeans—imagine the pain) the second year. The college had the same curriculum for all students regardless of their department until the third year, and therefore most of the time was spent on the common subjects: maths, physics, etc. While we moved through these subjects with a good pace (and I could hardly keep up), programming was very basic and moving very slow (they’d explain `if` statements, loops and functions the whole first year).
- I had extreme drowsiness most of the time because I find it super hard to wake up at 7am every day and take an hour of metro to get to the uni. Combined with indifference to subjects like physics, it resulted in me stopping to take notes mid semester and just sleeping through most of the lessons.
- No students from my group cared about programming. Most saw programming as a necessary evil. As a result, teachers didn’t care much either. I quickly became disillusioned after trying to impress them. One teacher gave a problem (“write a program that converts roman numerals to proper numbers without using a single integer variable” or something similar) and told the class no student has solved it so far. I spent a night solving it in F# and when I brought it to him, he wasn’t interested. Another time, another teacher asked me to write a snippet of code in C and started picking on me in front of the class for using some tiny computation inside a loop, when it was clearly hoistable by the compiler and not expensive anyway. Another time, I was asked to do the course work in C (write three functions that imitate oscillator and print the table of its values over time), and after finishing it in two hours, I wanted to show something more, so I wrote a C# app that would talk over P-Invoke to that C library and let the user actually see the oscillation in real time on a graph and add custom transformations a la GarageBand to it, with function expressions compiled on the fly via .NET Reflection API. One of the teachers decided I failed the course work, and it was only thanks to the other teacher who vouched for me that I received a good grade for it. 
- It got to the point of ridiculousness when I skipped 10 English lessons because I couldn’t bear to waste time there, and wanted to write the exam right away, and the teacher agreed that would have been better. Of course, when the time came, the teacher wouldn’t let me write the exam—I had to pay money for the “missing lessons lecture” where folks like me sat for an hour pretending we’re “cathing up”. Only then was I allowed to write the exam. The idea of paying for what I know instead of what I didn’t know was when I hated the uni and decided I’m done with it.

I think most people there remember me either as an annoying know-it-all during programming lessons, or as a lazy sleepyhead copycat on the last row of any other lesson. I was all of these, but starting with the second year, I got a job and realized I don’t want to be part of this toxic environment anymore when I can solve real problems for real people, receive money and respect for it, and have fun and a good sleep.

**Comment by gaearon** [comment]
The post above sounds a lot like bragging so let's put this in perspective: there was hardly any competition. This uni wasn't a top choice for programmers (I didn't get into the top choice unis) and hardly anyone there was thinking about becoming a software developer. I was only a know-it-all because I knew a bit about programming surrounded by people who didn't care about it in the first place, just like I didn't care about physics. I was (and still am) quite ignorant about many topics (e.g. compilers, data structures, algorithms, machine learning, graph traversal, etc) and I wish uni filled _that_ gap but it didn't.

**Comment by jimthedev** [comment]
Thanks for writing this. I had a very very similar experience.

**Comment by gaearon** [comment]
Continuation: https://github.com/gaearon/ama/issues/53#issuecomment-142318849

**Comment by eush77** [comment]
@gaearon Thank you for such a wonderful answer!

Do you mind sharing what university was that?

**Comment by gaearon** [comment]
http://www.sut.ru/teaching/ft/ssskvt/kaf-ss

**Comment by aulizko** [comment]
I have to say this: in Russia, uni teachers are underpaid. I mean - if you are a good programmer, you have no reason to go at the university and teach someone because you'll have much more money by working as a programmer. 
And that is really sorrowfully because most positions of the teachers are filled with loosers who can't find a better job. 
There are (yes there **really** are) exceptions. Very exceptional and very bright, enthusiasm-driven people that do teach because they love it, but their counts are low. 

And there is another problem with IT-related uni courses: the surface of IT-world changes so quickly so it's almost impossible to teach anything usable besides fundamental CS-knowledge. 
No point to teach students with objective-c when tomorrow they will write programms with swift. 
And there is a problem with russian-language IT-related school-books. Say, book was written in 2004, translated at 2006, and has been approved as a school book at 2008. The whole technology may be dead at 2008, but uni only starts to adopt that outdated book.

**Comment by HurricaneJames** [comment]
Only useful thing I learned in the first two years, "never take a class before 10am." Third and fourth years were much better. Grad school was actually a lot of fun, though I would not have done it if I had not been working on an awesome research team before I started.

Computer science is more like art than engineering. Students in both fields can get by just fine without the degree. Yet they miss a lot of important stuff by not studying at all.

Do not feel too bad about going to a "top-choice" school. I knew a lot of people who went to those schools over here. Their experiences were almost identical. Their piece of paper was worth more and they had more opportunities for side projects, but their loans were far more punishing.

Fortunately, an awful lot of people in our industry feel the same way and are starting to change things. Hopefully, by the time my daughter is 18, she will have different education choices that confer the same status as university (or better).

**Comment by damassi** [comment]
Really fantastic answer. I feel like all of your responses to education questions should be printed into a manifesto and dropped from airplanes across the US; the stakes are so high here, and college is so expensive, that it becomes a very real and literal health issue later in life if a path is chosen for the wrong reasons.

**Comment by olegakbarov** [comment]
Wow, i have exactly the same experience with SUT. I mean _exactly_ !
