### ISSUE TITLE
What are you thoughts about "war" - css vs inline styles?

### ISSUE THREAD

**Issue by yodairish** [gaearon/ama#50]
As we can see in results here: https://css-tricks.com/poll-results-for-managing-styles-with-javascript/ tons of people at least not ready for inline styles.
So, what are you think where is all comes? Inline styles "win" and most of big projects begin to use it and browsers will play around it, or mb people don't accept it and this comes to a standstill?

**Comment by serapath** [comment]
I'm interested too learn about that too :-) But [`jss`](https://github.com/jsstyles/jss) shows you can also manage stylesheets, not just inline-styles from javascript.

@gaearon
what do you think about `jss` and/or [`css-modules`](https://github.com/css-modules/css-modules) in combination with things like [`hyperstyles`](https://github.com/colingourlay/hyperstyles)

**Comment by LorbusChris** [comment]
+1 :)

**Comment by tychota** [comment]
+1:)

**Comment by gaearon** [comment]
It's hard to say! I don't have a clear preference right now because I haven't worked on a product for almost half a year, and we were just barely starting to sometimes use inline styles when I left, so I haven't really played with these solutions enough.

I think, code-wise, I prefer the inline styles model. It doesn't need to correspond to inline styles in the implementation: for example [jsxstyle](https://github.com/petehunt/jsxstyle) treats CSS as an implementation detail, and it works as inline styles in development, but can be extracted into a CSS bundle in production thanks to static analysis. Using static analysis for this is appealing to me because it lets you write code using a single language (JS), but still perform tasks like auto-prefixing, optimization and dead-code elimination at the compile time.

There are, however, tradeoffs and inconveniences you already know: editing or debugging inline styles in browser isn't very nice, it's harder to do CSS animations or media queries. I think, as we get better JavaScript APIs for these things, and more frameworks start adopting React's declarative rendering model, inline styles (or, really, specify-as-inline-styles-but-compile-to-whatever) solutions will become mainstream. In the meantime, CSS modules strike a pretty good balance between the benefits of style isolation and the incidental complexity introduced by many inline style tools. But I'm also looking forward to more tools like [jsxstyle](https://github.com/petehunt/jsxstyle).
