### ISSUE TITLE
What do you think about npm having so many modules

### ISSUE THREAD

**Issue by kentcdodds** [gaearon/ama#62]
Hi, I recently [tweeted](https://twitter.com/kentcdodds/status/650034445974568960):

![screen shot 2015-10-05 at 9 19 12 am](https://cloud.githubusercontent.com/assets/1500684/10284634/2bcb5b14-6b42-11e5-937e-c01947835a82.png)

> So is there going to be some kind of crazy celebration when @npmjs hits a quarter of a million packages in the next 6 months or so?
> Or is this something to lament? #lessismore? @npmjs

Curious what your thoughts on the matter are :-)

**Comment by gaearon** [comment]
I like many modules.

I think NPM encourages people to try publishing stuff because “it doesn't have to be big to be useful”.
So your first open source module might be something silly but you will publish it and get in the game.

Of course, like with app store, quality isn't always great, but you want to check what you rely on anyway.

**Comment by kentcdodds** [comment]
I agree with you :-) I think that @hughsk also gave a terrific answer to this question. https://github.com/hughsk/ama/issues/21
