### ISSUE TITLE
What is the biggest mystery to you?

### ISSUE THREAD

**Issue by kentcdodds** [gaearon/ama#63]
What is the one question that perplexes you most, but you don't have a reasonable hope to know the answer to?

ref: https://github.com/kentcdodds/ama/issues/37 :smile:

**Comment by gaearon** [comment]
That's an easy one!

https://en.wikipedia.org/wiki/Hard_problem_of_consciousness

I know that I am conscious (based on my first-hand experience). I feel joy and pain, I can appreciate colors, music, ideas, speech, a good movie. Of course I can't _know_ for sure that other people are conscious, but given that there's no reason why I should be special, I assume other people are conscious too. Solipsism is silly.

I don't know whether this extends to animals, but they exhibit the same behaviors I associate with at least partial consciousness, such as pain, pleasure, play, etc. So I think my cat is also conscious to some extend, even if he does not watch movies. Whether consciousness is measurable, and whether humans are more conscious than other animals, or are just better at reasoning, time and symbol manipulation, I don't know.

Next, I'm a materialist. I also don't believe in supernatural explanations. At any point in time, we could take something that science doesn't understand yet, and declare it a mystery. We could have done this with the night sky, medicine, atoms, magnetism, or genes. However, every time somebody discovered the deeper foundations, weird laws that nevertheless are better at describing the world better than a comfy story. This is why it doesn't make sense to me that consciousness is somehow special and is "magical".

I don't believe that there is something inherently special about humans, or animals, that gives them consciousness. I believe we are lumps of matter, just like stars, or donuts, and that we don't possess immortal souls, or something like this. I know many people are horrified at this thought, but it makes more sense to me than to assume otherwise.

Therefore, there are lumps of matter like me, you, and my cat, that seem to know pain, and pleasure, and color, and music. However I find it hard to grant these experiences to a coffee machine, or a chair, a kettle, a microbe, or a human embryo consisting of one cell.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/06/HumanEmbryogenesis.svg/1560px-HumanEmbryogenesis.svg.png)

No, I don't think a single-cell embryo has experiences. But I definitely do have experiences. And I was once a single cell. So when did I start having experiences? What brought the "specialness" into the lump of matter that I am? How does this "specialness" get preserved when cells of my body are replaced one by one?

Again, I don't think there's any supernatural explanation to this. That would really upset me because it doesn't fit everything else I know about the world. What is a natural explanation? Most scientists associate consciousness with brain activity. Indeed, I have a brain, and you have a brain, and my cat has a brain, and my kettle doesn't. So maybe brains are somehow "special" and give rise to conscious experiences.

Except, brains are just matter. If we let ourselves think there's a "mind" somewhere and a brain acts like an antenna to connect to it, then there's point in a brain where physical laws are violated. I find this idea nonsensical. Basically it's "and then magic happens" people have been saying for thousands of years for anything they can't explain yet. So I reject dualism.

So if brains are matter, does the _matter itself_ give rise to consciousness? But then smashing a person's head wouldn't make them dead. It seems that it's the organization that matters, not the material. There's also this mind experiment: imagine you're replacing neurons in the head one by one with their artificial counterparts. Surely if they behave the same way electrically, the system on a whole would not change? I think not. But then you can replace all neurons eventually, and the brain is artificial. Would it suddenly lose consciousness? I don't know but it feels wrong to assume so. Of course, one is free to not trust a computer if it says it's conscious, but don't forget we grant the "free pass" at consciousness to every human even though they can't prove they are conscious either!

So, I guess, I'm a functionalist, materialist, and reductionist. I believe that things can be explained, and there's nothing special about humans, animals, or organic brains. However I know that I am the only thing I'm _sure_ is conscious, and I'm pretty confident other humans (and some life forms) are conscious too. _What_ explains this consciousness, whether it can be replicated artificially, and whether this question even makes sense, is the biggest mystery to me.

**Comment by kentcdodds** [comment]
That's deep. Thanks for sharing your insights :-)

**Comment by bwatts** [comment]
Late to the party :smile:

This was my biggest question for a long time as well, which I found it addressed in an unexpected place: [The Moral Animal](http://www.amazon.com/The-Moral-Animal-Evolutionary-Psychology/dp/0679763996). The field of Evolutionary Psychology looks at the development of the mind alongside the biology.

The crux is that _consciousness is the result of natural selection in a status hierarchy_.

Awareness of self arises as a result of our interactions. Defined in terms of some boundary (cell wall, skin), these transactions produce a form of accounting that informs who to trust, who to avoid, and who might have food they are willing to share.

Power structures influence the propagation of genes to future generations, where successful lineages find food and mates enough within those hierarchies. As the dynamics grow in complexity, knowledge of past and future becomes more valuable.

Those skilled in predicting the future, at projecting "self" and "others" beyond an immediate horizon, retain a natural advantage. This leads to a scale on which your cat's genetic history has simply not been "milled" against enough social scenarios to produce complex, future-aware consciousness.

This is been a very interesting and fruitful line of thought for me in the face of the big mystery. Thanks for sharing!
