### ISSUE TITLE
Procrastination

### ISSUE THREAD

**Issue by yodairish** [gaearon/ama#69]
Do you have such moments? If so, how you deal with it?

**Comment by gaearon** [comment]
Yeah, quite a lot actually. I usually acknowledge to myself that I want to spend time doing nothing, and go watch a TV show with my wife, play some video game I haven't played since childhood, or read reviews for TV episodes I watched. I know I'm wasting time but I'm letting myself to do this and I explicitly don't fight it. This way, eventually I get bored and I want to work. :-)

**Comment by wle8300** [comment]
Yea man! Don't follow the post-modern narrative of productivity: The More You Do The More You Are. You gotta have time for yourself... "down time" and "up time." It's how we were designed to function.
