### ISSUE TITLE
How is your experience in London?

### ISSUE THREAD

**Issue by ghost** [gaearon/ama#82]
what you liked / disliked, housing, culture, friends, tech scene...

**Comment by gaearon** [comment]
I really like London. It’s rather expensive but in every other regard it’s my favorite city so far. I think it combines the parts of Europe and America I enjoy the most. I can speak English, everybody has a really nice accent, many people are style conscious and well dressed, and people have very diverse occupations. There is no focus on tech unlike SF, and I enjoy this. 

I don’t really know about friends or tech scene because at the moment I don’t live a very social lifestyle. But I like the people here and I hope I’ll make some after I settle down a little more and start interacting with folks outside my job.
