### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by kennetpostigo** [gaearon/ama#86]
How long have you been developing?

Best way to approach libraries to understand how they work under the hood?

Tips for organizing a library and decisions to create abstractions?

Any tips?

Thank you for your open source work.

**Comment by gaearon** [comment]
> How long have you been developing?

I started learning programming when I was about 13, but I don’t think I wrote any real apps until about 17. I’m close to 24 now.

> Best way to approach libraries to understand how they work under the hood?

Fix bugs in them!

> Tips for organizing a library and decisions to create abstractions?

That sounds too broad to answer :smile: .
1. Make common case simple, complex cases possible
2. Pick your battles and _what_ your library is opinionated about
3. Don’t be opinionated unless you can provide the user some benefits from the constraints you enforce
4. Aim for smaller API surface area because it’s super expensive
5. Trust people

> Any tips?

I have some tips here: http://outlierdeveloper.com/developer-qa-creativity-productivity-and-the-future/
