### ISSUE TITLE
How to achieve the perfect balance between product development and technical tasks?

### ISSUE THREAD

**Issue by agentcooper** [gaearon/ama#9]

**Comment by gaearon** [comment]
I only have startup experience so YMMV.

In my experience if you tell the product team “hey folks, our options is to either ship this a week faster, and then screw up next month, or take a week to fix something and then we'll move faster”, they'll tell what they want, and then you can plan accordingly.

**Comment by gaearon** [comment]
Some technical tasks (assuming you mean infrastructure, updating dependencies, switching to better libraries, etc) are best to be fit into product plan. For example, for each 3 new features in product plan, add 1 infra task related to them, and push the product team to accept it as valid. It really depends on how much say you have in the process, and whether the product team trusts you to make the right decisions.

I think presenting tradeoffs fairly is the best way to have people trust you when you say “you're going to regret not doing this”. Of course, you also need to constrain yourself and be very disciplined about technical issues. If you're doing something “just because you think it _might_ turn out cool”, do this in free time or when you have no pending tasks and want to have some fun. As soon as you feel like going nowhere (2 days max), abandon it and publish a branch for others to see, discuss and maybe get back to it later.

**Comment by gaearon** [comment]
Also, most of the times, if you don't feel you're _wasting your time_ developing product features (e.g. module with countless bugs), don't bother improving your tech. Some technical tasks just suck up time and amount to no good in the end. It's especially clear when your product actually fails, and you see how worthless that "cool rewrite" was.

On the other hand, keep yourself in shape by doing small side projects with new stuff. This will let you recognize when you actually _are_ wasting time by not adopting some new technique. Then, next time you're working on a product feature, try to squeeze in that technical task. In case it's too expensive to integrate, and there's no immediate return on investment, you might want to hold off until the next "big rewrite" (e.g. complete redesign) which is a good time to try new tech.
